
INSERT INTO `tb_admin` VALUES(
    '',
    'adm',
    'adm',
    'adm',
    'adm'
);

INSERT INTO `tb_ong` VALUES(
    '1',
    'Só Vira Latas',
    'SVL',
    'svl@gmail.com',
    'SVLCNPJ',
    'Uma ong que resgata, cuida, trata e oferece animais à adoção.',
    'Mato Grosso',
    'Cuiabá',
    '(22)9429-2142',
    'svl123',
    'imgpadrao.png'
);

INSERT INTO `tb_ong` VALUES(
    '2',
    'IFPR Doações',
    'IFDoe',
    'doacoes@ifpr.edu.br',
    'IFPRCNPJ',
    'Uma ONG feita por alunos do IFPR com o intuito de promover a doação de animais.',
    'Paraná',
    'Foz do Iguaçu',
    '(22)9429-2142',
    'ifpr',
    'imgpadrao.png'
);
INSERT INTO `tb_ong` VALUES(
    '3',
    'Gatinhos Fofos',
    'GF',
    'gatosfofos@gmail.com',
    'GFCNPJ',
    'Uma ONG focada em adoção de gatos abandonados.',
    'Rio Grande do Sul',
    'Porto Alegre',
    '(22)9429-2142',
    'gf123',
    'imgpadrao.png'
);
INSERT INTO `tb_publicacao` VALUES(
    '1',
    'Leandro',
    'Labrador',
    'Macho',
    'Chocolate',
    '2 meses',
    'Um pet muito tímido',
    'São Paulo',
    'São Bernardo do Campo',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'cachorro.png',
    '',
    '',
    ''
);
INSERT INTO `tb_publicacao` VALUES(
    '2',
    'João',
    'Labrador',
    'Macho',
    'Cinza',
    '5 anos',
    'Um pet muito amigável',
    'Paraná',
    'Curitiba',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'gato.jpg',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '3',
    'José',
    'Persa',
    'Macho',
    'Chocolate',
    '2 anos',
    'Um pet muito amigo',
    'São Paulo',
    'São Bernardo do Campo',
    '(11)94922-4212',
    'pet@gmail.com',
    'gato2.jpg',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '4',
    'João',
    'Labrador',
    'Macho',
    'Cinza',
    '5 anos',
    'Um pet muito amigável',
    'Paraná',
    'Curitiba',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'gato.jpg',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '5',
    'Leandro',
    'Labrador',
    'Macho',
    'Chocolate',
    '2 meses',
    'Um pet muito tímido',
    'São Paulo',
    'São Bernardo do Campo',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'cachorro.png',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '6',
    'João',
    'Labrador',
    'Macho',
    'Cinza',
    '5 anos',
    'Um pet muito amigável',
    'Paraná',
    'Curitiba',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'gato.jpg',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '7',
    'Leandro',
    'Labrador',
    'Macho',
    'Chocolate',
    '2 meses',
    'Um pet muito tímido',
    'São Paulo',
    'São Bernardo do Campo',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'cachorro.png',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '8',
    'João',
    'Labrador',
    'Macho',
    'Cinza',
    '5 anos',
    'Um pet muito amigável',
    'Paraná',
    'Curitiba',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'gato.jpg',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '9',
    'Leandro',
    'Labrador',
    'Macho',
    'Chocolate',
    '2 meses',
    'Um pet muito tímido',
    'São Paulo',
    'São Bernardo do Campo',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'cachorro.png',
  '',
    '',
    '');
INSERT INTO `tb_publicacao` VALUES(
    '10',
    'João',
    'Labrador',
    'Macho',
    'Cinza',
    '5 anos',
    'Um pet muito amigável',
    'Paraná',
    'Curitiba',
    '(11)94922-4212',
    'joaodasilva@gmail.com',
    'gato.jpg',
  '',
    '',
    '');
